snake_paths = list()
snake_paths$test_runs_ckmr_eval = list()
snake_paths$test_runs_ckmr_eval$output = list()
snake_paths$test_runs_ckmr_eval$log = list()
snake_paths$test_runs_ckmr_eval$benchmark = list()
snake_paths$prod_runs_ckmr_eval = list()
snake_paths$prod_runs_ckmr_eval$output = list()
snake_paths$prod_runs_ckmr_eval$log = list()
snake_paths$prod_runs_ckmr_eval$benchmark = list()
snake_paths$fishery_data_eval = list()
snake_paths$fishery_data_eval$output = list()
snake_paths$fishery_data_eval$log = list()
snake_paths$fishery_data_eval$benchmark = list()
snake_paths$make_pedigree = list()
snake_paths$make_pedigree$output = list()
snake_paths$make_pedigree$log = list()
snake_paths$make_pedigree$benchmark = list()
snake_paths$make_pedigree$log$log = list()
snake_paths$make_pedigree$log$log$regex = "results/logs/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/ped_rep-(.*)/ped_rlog.txt"
snake_paths$make_pedigree$log$log$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "ped_rep")
snake_paths$make_pedigree$log$log$glob = "results/logs/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/ped_rep-*/ped_rlog.txt"
snake_paths$make_pedigree$log$snake_obj = list()
snake_paths$make_pedigree$log$snake_obj$regex = "results/logs/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/ped_rep-(.*)/make_pedigree_snake_obj.txt"
snake_paths$make_pedigree$log$snake_obj$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "ped_rep")
snake_paths$make_pedigree$log$snake_obj$glob = "results/logs/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/ped_rep-*/make_pedigree_snake_obj.txt"
snake_paths$make_pedigree$benchmark$bm = list()
snake_paths$make_pedigree$benchmark$bm$regex = "results/benchmarks/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/ped_rep-(.*)/ped_rlog.txt"
snake_paths$make_pedigree$benchmark$bm$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "ped_rep")
snake_paths$make_pedigree$benchmark$bm$glob = "results/benchmarks/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/ped_rep-*/ped_rlog.txt"
snake_paths$make_pedigree$output$rdata = list()
snake_paths$make_pedigree$output$rdata$regex = "results/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/ped_rep-(.*)/ped.Rdata"
snake_paths$make_pedigree$output$rdata$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "ped_rep")
snake_paths$make_pedigree$output$rdata$glob = "results/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/ped_rep-*/ped.Rdata"
snake_paths$estimate = list()
snake_paths$estimate$output = list()
snake_paths$estimate$log = list()
snake_paths$estimate$benchmark = list()
snake_paths$estimate$output$rds = list()
snake_paths$estimate$output$rds$regex = "results/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/analysis_objs.rds"
snake_paths$estimate$output$rds$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$output$rds$glob = "results/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/analysis_objs.rds"
snake_paths$estimate$output$key_obs = list()
snake_paths$estimate$output$key_obs$regex = "results/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/key_output_objs.rds"
snake_paths$estimate$output$key_obs$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$output$key_obs$glob = "results/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/key_output_objs.rds"
snake_paths$estimate$output$admb_arena = list()
snake_paths$estimate$output$admb_arena$regex = "directory(results/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/admb_arena)"
snake_paths$estimate$output$admb_arena$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$output$admb_arena$glob = "directory(results/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/admb_arena)"
snake_paths$estimate$log$log = list()
snake_paths$estimate$log$log$regex = "results/logs/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/estimate_rlog.txt"
snake_paths$estimate$log$log$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$log$log$glob = "results/logs/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/estimate_rlog.txt"
snake_paths$estimate$log$snake_obj = list()
snake_paths$estimate$log$snake_obj$regex = "results/logs/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/snake_obj.rds"
snake_paths$estimate$log$snake_obj$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$log$snake_obj$glob = "results/logs/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/snake_obj.rds"
snake_paths$estimate$benchmark$bm = list()
snake_paths$estimate$benchmark$bm$regex = "results/benchmarks/POP-pop_mult-(.*)/MATING-mating-(.*)-ssf-(.*)-eofsr-(.*)-fec_known-(.*)/NSAMPYRS-(.*)/ped_rep-(.*)/ckmr_ssmult-(.*)/EST-rind_sd-(.*)-prop_sampled-(.*)-beta-(.*)-comp_bias-(.*)/EST2-mtHZ-(.*)-mtHZ_est-(.*)-et-(.*)/sample_by_sex-(.*)---ckmr_seed-(.*)---ri_seed-(.*)---cv_seed-(.*)---nll_type-(.*)/estimate.txt"
snake_paths$estimate$benchmark$bm$into = c("pop_mult", "mating", "ssf", "eofsr", "fec_known", "nsampyrs", "ped_rep", "ckmr_ssmult", "rind_sd", "prop_sampled", "beta", "comp_bias", "hzt", "hze", "et", "sample_by_sex", "ckmr_seed", "ri_seed", "cv_seed", "nll_type")
snake_paths$estimate$benchmark$bm$glob = "results/benchmarks/POP-pop_mult-*/MATING-mating-*-ssf-*-eofsr-*-fec_known-*/NSAMPYRS-*/ped_rep-*/ckmr_ssmult-*/EST-rind_sd-*-prop_sampled-*-beta-*-comp_bias-*/EST2-mtHZ-*-mtHZ_est-*-et-*/sample_by_sex-*---ckmr_seed-*---ri_seed-*---cv_seed-*---nll_type-*/estimate.txt"
